from __future__ import annotations

from ..api.v1.models import (
    AiDraftDecisionRequest,
    AiDraftDecisionResponse,
    AiFreeAgencyDecisionRequest,
    AiFreeAgencyDecisionResponse,
    AiFranchiseDirectionRequest,
    AiFranchiseDirectionResponse,
    AiProfileLookupRequest,
    AiProfileResponse,
    AiTradeDecisionRequest,
    AiTradeDecisionResponse,
    ChemistryCalculateRequest,
    ChemistryCalculateResponse,
    ConflictSimulateRequest,
    ConflictSimulateResponse,
    DraftGenerateRequest,
    DraftGenerateResponse,
    DynastyTrackRequest,
    DynastyTrackResponse,
    EraTransitionRequest,
    EraTransitionResponse,
    FranchiseOptimizeRequest,
    FranchiseOptimizeResponse,
    ProgressionSimulateRequest,
    ProgressionSimulateResponse,
    MoraleEvaluateRequest,
    MoraleEvaluateResponse,
    SeasonSimulateRequest,
    SeasonSimulateResponse,
    LockerRoomStatusResponse,
    PersonalityUpdateRequest,
    PersonalityUpdateResponse,
    TradeEvaluateRequest,
    TradeEvaluateResponse,
)


def get_tool_schemas() -> list[dict[str, object]]:
    return [
        {
            "name": "franchise_optimizer",
            "description": "Optimize franchise decisions for cap space and championship odds.",
            "input_schema": FranchiseOptimizeRequest.model_json_schema(),
            "output_schema": FranchiseOptimizeResponse.model_json_schema(),
        },
        {
            "name": "trade_evaluator",
            "description": "Evaluate trade fairness with age, contract, and value curves.",
            "input_schema": TradeEvaluateRequest.model_json_schema(),
            "output_schema": TradeEvaluateResponse.model_json_schema(),
        },
        {
            "name": "draft_generator",
            "description": "Generate modern-era draft classes with scouting confidence.",
            "input_schema": DraftGenerateRequest.model_json_schema(),
            "output_schema": DraftGenerateResponse.model_json_schema(),
        },
        {
            "name": "progression_simulator",
            "description": "Simulate progression and regression outcomes over multiple years.",
            "input_schema": ProgressionSimulateRequest.model_json_schema(),
            "output_schema": ProgressionSimulateResponse.model_json_schema(),
        },
        {
            "name": "season_simulator",
            "description": "Run a Monte Carlo season simulation with era pace adjustments.",
            "input_schema": SeasonSimulateRequest.model_json_schema(),
            "output_schema": SeasonSimulateResponse.model_json_schema(),
        },
        {
            "name": "dynasty_tracker",
            "description": "Score and summarize dynasty performance over a historical window.",
            "input_schema": DynastyTrackRequest.model_json_schema(),
            "output_schema": DynastyTrackResponse.model_json_schema(),
        },
        {
            "name": "era_transition_handler",
            "description": "Transition modern-era rule packs between supported seasons.",
            "input_schema": EraTransitionRequest.model_json_schema(),
            "output_schema": EraTransitionResponse.model_json_schema(),
        },
        {
            "name": "ai_trade_decision",
            "description": "Compute CPU trade behavior from GM personality, ownership, media pressure, and era.",
            "input_schema": AiTradeDecisionRequest.model_json_schema(),
            "output_schema": AiTradeDecisionResponse.model_json_schema(),
        },
        {
            "name": "ai_draft_decision",
            "description": "Compute CPU draft strategy decisions with personality-adjusted weighting.",
            "input_schema": AiDraftDecisionRequest.model_json_schema(),
            "output_schema": AiDraftDecisionResponse.model_json_schema(),
        },
        {
            "name": "ai_free_agency_decision",
            "description": "Compute CPU free agency strategy decisions with cap and ownership constraints.",
            "input_schema": AiFreeAgencyDecisionRequest.model_json_schema(),
            "output_schema": AiFreeAgencyDecisionResponse.model_json_schema(),
        },
        {
            "name": "ai_franchise_direction",
            "description": "Classify franchise direction with confidence and trigger factors.",
            "input_schema": AiFranchiseDirectionRequest.model_json_schema(),
            "output_schema": AiFranchiseDirectionResponse.model_json_schema(),
        },
        {
            "name": "ai_profile_lookup",
            "description": "Resolve normalized team AI profile inputs for caller-managed request-driven drift.",
            "input_schema": AiProfileLookupRequest.model_json_schema(),
            "output_schema": AiProfileResponse.model_json_schema(),
        },
        {
            "name": "locker_room_chemistry_calculate",
            "description": "Calculate dynamic locker-room chemistry for a team profile.",
            "input_schema": ChemistryCalculateRequest.model_json_schema(),
            "output_schema": ChemistryCalculateResponse.model_json_schema(),
        },
        {
            "name": "locker_room_personality_update",
            "description": "Generate or manually update player personalities and locker-room hierarchy.",
            "input_schema": PersonalityUpdateRequest.model_json_schema(),
            "output_schema": PersonalityUpdateResponse.model_json_schema(),
        },
        {
            "name": "locker_room_conflict_simulate",
            "description": "Simulate locker-room conflicts with queue decay and escalation.",
            "input_schema": ConflictSimulateRequest.model_json_schema(),
            "output_schema": ConflictSimulateResponse.model_json_schema(),
        },
        {
            "name": "locker_room_morale_evaluate",
            "description": "Evaluate player morale and gameplay impacts from chemistry and conflicts.",
            "input_schema": MoraleEvaluateRequest.model_json_schema(),
            "output_schema": MoraleEvaluateResponse.model_json_schema(),
        },
        {
            "name": "locker_room_status_lookup",
            "description": "Fetch profile-scoped locker-room status for a team/season/era.",
            "input_schema": {
                "type": "object",
                "properties": {
                    "team_id": {"type": "string"},
                    "profile_id": {"type": "string"},
                    "season": {"type": "string"},
                    "era": {"type": "string"},
                    "seed": {"type": "integer"},
                },
                "required": ["team_id", "profile_id", "season", "era"],
                "additionalProperties": False,
            },
            "output_schema": LockerRoomStatusResponse.model_json_schema(),
        },
    ]
